### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by RajeshRamayan** [FilipS90/IT-Bootcamp---final-project#1]
Good day sir! I would have want to report this error I get from this code:

> Exception in thread "main" java.lang.Error: Unresolved compilation problem

I clone your repo, but I error when I run it. You can fix this? It not work

**Comment by FilipS90** [comment]
Hi Rajesh,

The code works just fine, I just tested it.
You need to do a couple of things first, in order to run it.

1. Download database file from this link https://gofile.io/?c=kpVUZ6 and put the file
in the correct folder to match the path in the project;
2. Download knjiga and sqlite files from the repo, I just added them. Build path for project
and import sqlite driver to it;
3. Adjust the path in class Knjiga -> method napraviTabelu() to match your path of the Dictionary.db.
4. Put knjiga file in your package with the rest of classes.

Let me know how it goes.

**Comment by RajeshRamayan** [comment]
Youre a motheryaker, it not work, it error

**Comment by FilipS90** [comment]
The code is fine, have a good day.
